apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-awesome-service
spec:
  template:
    spec:
      containerConcurrency: 20
      containers:
      - image: "us-central1-docker.pkg.dev/my-project/my-repo/my-image:TAG"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '2'
            memory: 1Gi
      timeoutSeconds: 300