name: yq TAG and maven dep. cache

on:
  push:
    branches:
      - main

# env:
#   PROJECT_ID: "YOUR_GCP_PROJECT"
#   GAR_LOCATION: "us-central1"
#   REPOSITORY: "ARTIFACT_REPO_NAME"
#   SERVICE: "CLOUD_RUN_SERVICE_NAME"
#   REGION: "us-central1"

jobs:
  deploy:
    # Get source code 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven using cache test
        run: mvn -B package --file pom.xml
      - name: Hydrate image tag in Cloud Run metadata.yml 
        uses: mikefarah/yq@master
        with:
          cmd: echo $GITHUB_SHA && cat metadata.yaml && yq e -i '.spec.template.spec.containers[0].image = "us-central1-docker.pkg.dev/my-project/my-repo/my-image:" + env(GITHUB_SHA)' metadata.yaml && cat metadata.yaml
